version: '3.8'

services:
  backend:
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT: backend
    ports:
      - '4000:4000'
    environment:
      TASK_NAME: '${APP_MODE}'
    depends_on:
      - reporting
      - statistics
  reporting:
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT: reporting
        PORT: 3000
    ports:
      - '3001:3000'
    environment:
      TASK_NAME: '${APP_MODE:-prod}'
    depends_on:
      - postgres
  statistics:
    deploy:
      replicas: 1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT: statistics
        PORT: 3000
    ports:
      - '3002:3000'
    environment:
      TASK_NAME: '${APP_MODE:-prod}'
    depends_on:
      - postgres
